import { ArrowLeft } from "lucide-react";
import { useLanguage } from "@/i18n/LanguageContext";

interface PrivacyPolicySectionProps {
  onBack: () => void;
}

const SECTIONS_RO = [
  {
    title: "1. Ce date colectăm",
    body: "Colectăm informațiile pe care ni le oferi direct (nume, poză, poziție, echipă, videoclipuri de teste, postări, mesaje) și date tehnice generate de folosirea aplicației (activitate, aprecieri, urmăritori, ora ultimei conectări).",
  },
  {
    title: "2. Cum folosim datele",
    body: "Datele tale sunt folosite pentru a-ți afișa profilul altor utilizatori conform setărilor tale de confidențialitate, pentru a-ți arăta conținut relevant în comunitate, pentru verificarea conturilor de tip Descoperitor și pentru a îmbunătăți funcționarea aplicației.",
  },
  {
    title: "3. Cu cine sunt distribuite",
    body: "Nu vindem datele tale către terți. Informațiile din profil sunt vizibile altor utilizatori conform setărilor tale de confidențialitate cont. Fișierele (poze, videoclipuri, documente) sunt stocate securizat și accesibile doar persoanelor autorizate să vadă conținutul respectiv.",
  },
  {
    title: "4. Controlul tău asupra datelor",
    body: "Poți oricând să-ți modifici setările de confidențialitate, să blochezi sau restricționezi alți utilizatori, să ștergi postări sau mesaje, și să-ți ștergi definitiv contul din secțiunea Setări → Contul tău.",
  },
  {
    title: "5. Securitate",
    body: "Folosim măsuri tehnice și organizatorice pentru a proteja datele tale împotriva accesului neautorizat, pierderii sau utilizării abuzive.",
  },
  {
    title: "6. Păstrarea datelor",
    body: "Păstrăm datele tale atât timp cât contul tău este activ. La ștergerea contului, datele asociate sunt eliminate definitiv, cu excepția cazurilor în care păstrarea lor este cerută de lege.",
  },
  {
    title: "7. Modificări ale acestei politici",
    body: "Putem actualiza această politică de confidențialitate periodic. Continuarea folosirii aplicației după o actualizare reprezintă acceptarea noii politici.",
  },
  {
    title: "8. Contact",
    body: "Pentru întrebări legate de datele tale sau această politică, ne poți contacta din secțiunea Ajutor și asistență a aplicației.",
  },
];

const SECTIONS_EN = [
  {
    title: "1. What data we collect",
    body: "We collect the information you give us directly (name, photo, position, team, test videos, posts, messages) and technical data generated by using the app (activity, likes, followers, last login time).",
  },
  {
    title: "2. How we use your data",
    body: "Your data is used to show your profile to other users according to your privacy settings, to show you relevant content in the community, to verify Scout-type accounts, and to improve how the app works.",
  },
  {
    title: "3. Who we share it with",
    body: "We don't sell your data to third parties. Profile information is visible to other users according to your account privacy settings. Files (photos, videos, documents) are stored securely and only accessible to people authorized to see that content.",
  },
  {
    title: "4. Your control over your data",
    body: "You can change your privacy settings at any time, block or restrict other users, delete posts or messages, and permanently delete your account from Settings → Your account.",
  },
  {
    title: "5. Security",
    body: "We use technical and organizational measures to protect your data against unauthorized access, loss, or misuse.",
  },
  {
    title: "6. Data retention",
    body: "We keep your data for as long as your account is active. When you delete your account, associated data is permanently removed, except where retention is required by law.",
  },
  {
    title: "7. Changes to this policy",
    body: "We may update this privacy policy periodically. Continuing to use the app after an update means you accept the new policy.",
  },
  {
    title: "8. Contact",
    body: "For questions about your data or this policy, you can reach us from the Help and support section of the app.",
  },
];

export default function PrivacyPolicySection({ onBack }: PrivacyPolicySectionProps) {
  const { lang } = useLanguage();
  const sections = lang === "ro" ? SECTIONS_RO : SECTIONS_EN;

  return (
    <div className="flex flex-col h-full bg-white">
      <div className="relative flex items-center px-4 py-3 border-b border-gray-200 shrink-0">
        <button onClick={onBack} className="p-1 text-gray-500 hover:text-gray-900">
          <ArrowLeft className="h-5 w-5" />
        </button>
        <h2 className="absolute left-1/2 -translate-x-1/2 font-heading text-sm tracking-wide text-gray-900 whitespace-nowrap">
          {lang === "ro" ? "Politica de confidențialitate" : "Privacy Policy"}
        </h2>
      </div>

      <div className="flex-1 overflow-y-auto px-5 py-5 space-y-5">
        <p className="text-xs text-gray-500 font-body">
          {lang === "ro" ? "Ultima actualizare: 2 septembrie 2026" : "Last updated: September 2, 2026"}
        </p>
        {sections.map((s) => (
          <div key={s.title}>
            <p className="text-sm font-semibold font-body text-gray-900 mb-1">{s.title}</p>
            <p className="text-sm text-gray-500 font-body leading-relaxed">{s.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
