
ALTER TABLE public.player_profiles
ADD COLUMN IF NOT EXISTS speed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS jumping INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS endurance INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS acceleration INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS defense INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS career_description TEXT;
